# Generated by Django 3.0.5 on 2022-05-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_toppings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'toppings'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
