# Generated by Django 3.0.5 on 2022-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20220506_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
